name: Test and Deploy Hexo Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Hexo Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Hexo and Dependencies
        run: |
          npm install -g hexo-cli
          npm install

      - name: Generate Hexo Site
        run: hexo generate

      - name: Clone Playwright Test Repository
        run: |
          git clone https://github.com/jar285/is373_devops.git
          cd is373_devops/tests
          npm install

      # Force reinstall Playwright Browsers without caching issues
      - name: Clean Playwright Cache
        run: rm -rf /home/runner/.cache/ms-playwright  # Clear previous browser installs

      - name: Install Playwright Browsers
        run: |
          echo "Installing Playwright browsers with dependencies"
          npx playwright install --with-deps --force  # Force reinstallation

      # Verify that Playwright browsers are installed correctly
      - name: Verify Playwright Browser Installation
        run: ls /home/runner/.cache/ms-playwright

      - name: Execute Playwright Tests
        run: |
          cd is373_devops/tests
          npx playwright test --config=../playwright.config.js

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'

    steps:
      - name: Checkout Hexo Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js for Deployment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Hexo and Dependencies for Deployment
        run: |
          npm install -g hexo-cli
          npm install

      - name: Regenerate Hexo Site
        run: hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
