name: Test and Deploy Hexo Site

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Hexo website repository
      - name: Checkout Hexo repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify the Node.js version

      # Clean Hexo cache and files
      - name: Clean Hexo cache and files
        run: npx hexo clean

      # Install dependencies for Hexo
      - name: Install dependencies
        run: npm install

      # Generate the static Hexo site
      - name: Generate Hexo site
        run: npx hexo generate

      # Start the Hexo server in the background
      - name: Start Hexo server
        run: |
          npx hexo server &
          echo $! > hexo.pid

      # Wait for the Hexo server to be ready
      - name: Wait for Hexo server to start
        run: npx wait-on http://localhost:4000

      # Clone Playwright test repository
      - name: Clone Playwright Test Repository
        run: |
          git clone https://github.com/jar285/is373_devops.git
          cd is373_devops/tests
          npm install

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: |
          cd is373_devops/tests
          npx playwright install --with-deps

      # Execute Playwright tests
      - name: Execute Playwright Tests
        run: |
          cd is373_devops/tests
          npx playwright test --config=../playwright.config.js

      # Stop the Hexo server after Playwright tests
      - name: Stop Hexo server
        if: always()
        run: kill $(cat hexo.pid)

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'

    steps:
      # Checkout the Hexo website repository
      - name: Checkout Hexo repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify the Node.js version

      # Clean Hexo cache and files
      - name: Clean Hexo cache and files
        run: npx hexo clean

      # Install dependencies for Hexo
      - name: Install dependencies
        run: npm install

      # Generate the static Hexo site for deployment
      - name: Generate Hexo site
        run: npx hexo generate

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hexo outputs the generated files to the 'public' directory
